### ISSUE TITLE
Portable Edition

### ISSUE THREAD

**Issue by vanja-san** [GiraffeSummer/Sims4Modmanager#2]
Can you make a portable version?
And please add screenshots! 😏 I pay attention to convenience of UI.

**Comment by GiraffeSummer** [comment]
That shouldn't be too hard I'll try releasing that soon, for now you could install it and copy the files from the install directory.

For the screenshots, I'm not great at creating proper screenshots, and putting them in the README, but I'll give it a shot

**Comment by vanja-san** [comment]
![изображение](https://user-images.githubusercontent.com/7201687/101684259-b6212e80-3a98-11eb-8b81-848afd613e75.png)

**Comment by GiraffeSummer** [comment]
I've added a portable version, thank you for suggesting this.

I know how to use snipping tool, I'm just not great with showing off what I've made, I'll ask some friends to help me. but thank you for helping anyway. It's much appreciated!

Feel free to report any other issues, or suggestions any time!
