### ISSUE TITLE
No start

### ISSUE THREAD

**Issue by vanja-san** [GiraffeSummer/Sims4Modmanager#3]
At startup, it hangs in the task manager, but there is no program window.

![изображение](https://user-images.githubusercontent.com/7201687/102002258-39f34900-3d2d-11eb-9318-8817daf2e7b2.png)

**Comment by GiraffeSummer** [comment]
is this the portable version, or the installed one, did you get any errors?
did you start it using the browser extension or via the exe/shortcut
Have you tried running it as administrator?

**Comment by vanja-san** [comment]
— Portable version.
— I run it through .exe.
— With administrator rights.

> 
> 
> is this the portable version, or the installed one, did you get any errors?
> did you start it using the browser extension or via the exe/shortcut
> Have you tried running it as administrator?

**Comment by GiraffeSummer** [comment]
You might need to install it for now as it needs it's registry data (this is required for the installation through the browser)
it might not launch because of that.
otherwise, it could be that you seem to be running it in 32 bit mode, not sure if that could be the problem, but it might be.
